name: CI

# run CI on pushes to main, and on all PRs (even the ones that target other
# branches)

on:
 push:
   branches: [main]
 pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Check sort order
      run: diff bandnames.txt <(sort -u bandnames.txt)
